# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kurs.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(636, 352)
        MainWindow.setMinimumSize(QtCore.QSize(403, 352))
        MainWindow.setMaximumSize(QtCore.QSize(636, 352))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        MainWindow.setPalette(palette)
        MainWindow.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tab = QtWidgets.QTabWidget(self.centralwidget)
        self.tab.setGeometry(QtCore.QRect(0, 0, 631, 331))
        self.tab.setObjectName("tab")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 80, 171, 181))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 60, 31, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(40, 60, 61, 16))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 31, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(40, 90, 61, 16))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 120, 21, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(40, 120, 61, 16))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(40, 30, 61, 16))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(10, 30, 31, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_12.setGeometry(QtCore.QRect(40, 151, 61, 16))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(10, 151, 31, 16))
        self.label_13.setObjectName("label_13")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(106, 28, 21, 16))
        self.label_16.setObjectName("label_16")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(107, 150, 41, 16))
        self.label_20.setObjectName("label_20")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(10, 5, 371, 71))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(10, 40, 71, 22))
        self.comboBox.setEditable(True)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(120, 30, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(120, 50, 31, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(160, 30, 70, 16))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 50, 70, 16))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(255, 30, 21, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(255, 50, 16, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(275, 30, 70, 16))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(275, 50, 70, 16))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(349, 29, 21, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(349, 48, 21, 16))
        self.label_15.setObjectName("label_15")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(85, 39, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_21 = QtWidgets.QLabel(self.widget)
        self.label_21.setGeometry(QtCore.QRect(10, 76, 351, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setGeometry(QtCore.QRect(189, 80, 191, 181))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_2.setGeometry(QtCore.QRect(6, 20, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(10, 43, 21, 16))
        self.label_24.setObjectName("label_24")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_13.setGeometry(QtCore.QRect(48, 44, 61, 16))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(117, 122, 21, 16))
        self.label_17.setObjectName("label_17")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(48, 96, 61, 16))
        self.lineEdit_9.setText("")
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 93, 31, 16))
        self.label_10.setObjectName("label_10")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(116, 93, 21, 16))
        self.label_18.setObjectName("label_18")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 119, 41, 20))
        self.label_12.setObjectName("label_12")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_11.setGeometry(QtCore.QRect(48, 124, 61, 16))
        self.lineEdit_11.setText("")
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_14.setGeometry(QtCore.QRect(48, 70, 61, 16))
        self.lineEdit_14.setText("")
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(10, 69, 31, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(115, 67, 61, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_3)
        self.label_27.setGeometry(QtCore.QRect(10, 148, 31, 16))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_3)
        self.label_28.setGeometry(QtCore.QRect(117, 145, 61, 21))
        self.label_28.setObjectName("label_28")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_15.setGeometry(QtCore.QRect(48, 150, 61, 16))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_29 = QtWidgets.QLabel(self.groupBox_3)
        self.label_29.setGeometry(QtCore.QRect(116, 45, 23, 13))
        self.label_29.setObjectName("label_29")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 270, 151, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_4.setGeometry(QtCore.QRect(388, 80, 231, 181))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox.setGeometry(QtCore.QRect(50, 23, 91, 22))
        self.spinBox.setMaximum(9999)
        self.spinBox.setObjectName("spinBox")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(10, 28, 33, 13))
        self.label_9.setObjectName("label_9")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_2.setGeometry(QtCore.QRect(50, 89, 91, 22))
        self.spinBox_2.setMaximum(999999999)
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(10, 89, 33, 13))
        self.label_23.setObjectName("label_23")
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        self.label_30.setGeometry(QtCore.QRect(10, 120, 33, 13))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.groupBox_4)
        self.label_31.setGeometry(QtCore.QRect(10, 152, 33, 13))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox_4)
        self.label_32.setGeometry(QtCore.QRect(147, 89, 13, 13))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox_4)
        self.label_33.setGeometry(QtCore.QRect(147, 120, 16, 13))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.groupBox_4)
        self.label_34.setGeometry(QtCore.QRect(147, 152, 16, 13))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.groupBox_4)
        self.label_35.setGeometry(QtCore.QRect(147, 26, 17, 13))
        self.label_35.setObjectName("label_35")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_8.setGeometry(QtCore.QRect(50, 120, 91, 22))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_16.setGeometry(QtCore.QRect(50, 152, 91, 22))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_36 = QtWidgets.QLabel(self.groupBox_4)
        self.label_36.setGeometry(QtCore.QRect(147, 55, 17, 22))
        self.label_36.setObjectName("label_36")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_3.setGeometry(QtCore.QRect(50, 55, 91, 22))
        self.spinBox_3.setMaximum(9999)
        self.spinBox_3.setObjectName("spinBox_3")
        self.label_37 = QtWidgets.QLabel(self.groupBox_4)
        self.label_37.setGeometry(QtCore.QRect(10, 55, 33, 22))
        self.label_37.setObjectName("label_37")
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setGeometry(QtCore.QRect(400, 80, 221, 16))
        self.label_19.setObjectName("label_19")
        self.tab.addTab(self.widget, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setToolTip(_translate("MainWindow", "<html><head/><body><p>Относительная разность показателей преломления сердцевины и оболочки<br><img src=\"./img/delta.jpg\"/></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Δ = "))
        self.lineEdit_5.setToolTip(_translate("MainWindow", "<html><head/><body><p>Относительная разность показателей преломления сердцевины и оболочки<br><img src=\"./img/delta.jpg\"/></p></body></html>"))
        self.label_7.setToolTip(_translate("MainWindow", "<html><head/><body><p>Числовая апертура<br><img src=\"./img/apertura.jpg\"/></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "NA = "))
        self.lineEdit_6.setToolTip(_translate("MainWindow", "<html><head/><body><p>Числовая апертура<br><img src=\"./img/apertura.jpg\"/></p></body></html>"))
        self.label_8.setToolTip(_translate("MainWindow", "<html><head/><body><p>Нормированная частота<center><img src=\"./img/norm_freq.jpg\"/></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "V = "))
        self.lineEdit_7.setToolTip(_translate("MainWindow", "<html><head/><body><p>Нормированная частота<center><img src=\"./img/norm_freq.jpg\"/></p></body></html>"))
        self.lineEdit_10.setToolTip(_translate("MainWindow", "<html><head/><body><p>Протяженность трассы (в км)</p></body></html>"))
        self.label_11.setToolTip(_translate("MainWindow", "<html><head/><body><p>Протяженность трассы (в км)</p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "L = "))
        self.lineEdit_12.setToolTip(_translate("MainWindow", "<html><head/><body><p>Потери в оптическом волокне<br/><img src=\"./img/poteri.jpg\"/></p></body></html>"))
        self.label_13.setToolTip(_translate("MainWindow", "<html><head/><body><p>Потери в оптическом волокне<br/><img src=\"./img/poteri.jpg\"/></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "α  = "))
        self.label_16.setText(_translate("MainWindow", "км"))
        self.label_20.setText(_translate("MainWindow", "дБ/км"))
        self.comboBox.setItemText(1, _translate("MainWindow", "1310 (к)"))
        self.comboBox.setItemText(2, _translate("MainWindow", "1550 (к)"))
        self.label.setText(_translate("MainWindow", "Длина волны:"))
        self.label_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Показатель преломления сердцевины</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "nc1 = "))
        self.label_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Показатель преломления оболочки</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "nо1 ="))
        self.lineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Показатель преломления сердцевины</p></body></html>"))
        self.lineEdit_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Показатель преломления оболочки</p></body></html>"))
        self.label_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>Диаметр сердцевины</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "d ="))
        self.label_5.setToolTip(_translate("MainWindow", "<html><head/><body><p>Диаметр оболочки</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "D = "))
        self.lineEdit_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Диаметр сердцевины</p></body></html>"))
        self.lineEdit_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>Диаметр оболочки</p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "мкм"))
        self.label_15.setText(_translate("MainWindow", "мкм"))
        self.label_22.setText(_translate("MainWindow", "нм"))
        self.comboBox_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Тип показателя преломления</p></body></html>"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Ступенчатый"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Градиентный"))
        self.label_24.setToolTip(_translate("MainWindow", "<html><head/><body><p>Количество мод<br><img src=\"./img/cislo_mod.jpg\"/></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "M ="))
        self.lineEdit_13.setToolTip(_translate("MainWindow", "<html><head/><body><p>Количество мод<br><img src=\"./img/cislo_mod.jpg\"/></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "пс"))
        self.lineEdit_9.setToolTip(_translate("MainWindow", "<html><head/><body><p>Хроматическая дисперсия<br><img src=\"./img/disp_hr.jpg\"/></p></body></html>"))
        self.label_10.setToolTip(_translate("MainWindow", "<html><head/><body><p>Хроматическая дисперсия<br><img src=\"./img/disp_hr.jpg\"/></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "τхр = "))
        self.label_18.setText(_translate("MainWindow", "пс"))
        self.label_12.setToolTip(_translate("MainWindow", "<html><head/><body><p>Поляризационно модовая дисперсия<br/><img src=\"./img/disp_pmd.jpg\"/></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "τпмд = "))
        self.lineEdit_11.setToolTip(_translate("MainWindow", "<html><head/><body><p>Поляризационно модовая дисперсия<br/><img src=\"./img/disp_pmd.jpg\"/></p></body></html>"))
        self.lineEdit_14.setToolTip(_translate("MainWindow", "<html><head/><body><p>Межмодовая дисперсия<br><img src=\"./img/disp_mm.jpg\"/></p></body></html>"))
        self.label_25.setToolTip(_translate("MainWindow", "<html><head/><body><p>Межмодовая дисперсия<br><img src=\"./img/disp_mm.jpg\"/></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "τмм = "))
        self.label_26.setToolTip(_translate("MainWindow", "<html><head/><body><p>Межмодовая дисперсия<br><img src=\"./img/disp_mm.jpg\"/></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "пс/(нм*км)"))
        self.label_27.setToolTip(_translate("MainWindow", "<html><head/><body><p>Дисперсия <br> <img src=\"./img/disp.jpg\"/></p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "τ = "))
        self.label_28.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "пс/(нм*км)"))
        self.lineEdit_15.setToolTip(_translate("MainWindow", "<html><head/><body><p>Дисперсия <br> <img src=\"./img/disp.jpg\"/></p></body></html>"))
        self.label_29.setToolTip(_translate("MainWindow", "<html><head/><body><p>Количество мод<br><img src=\"./img/cislo_mod.jpg\"/></p></body></html>"))
        self.label_29.setText(_translate("MainWindow", "мод"))
        self.pushButton_2.setText(_translate("MainWindow", "Очистить"))
        self.spinBox.setToolTip(_translate("MainWindow", "Количество разъемных соединений"))
        self.spinBox.setSpecialValueText(_translate("MainWindow", "Введите ..."))
        self.label_9.setToolTip(_translate("MainWindow", "Количество разъемных соединений"))
        self.label_9.setText(_translate("MainWindow", "Nрс ="))
        self.spinBox_2.setToolTip(_translate("MainWindow", "Строительная длина ВОЛС"))
        self.spinBox_2.setSpecialValueText(_translate("MainWindow", "Введите..."))
        self.label_23.setToolTip(_translate("MainWindow", "Строительная длина ВОЛС"))
        self.label_23.setText(_translate("MainWindow", "Lстр ="))
        self.label_30.setToolTip(_translate("MainWindow", "<html><head/><body><p>Максимальная длина участка регенерации ВОЛС<br><img src=\"./img/Lmax.jpg\"/></p></body></html>"))
        self.label_30.setText(_translate("MainWindow", "Lmax ="))
        self.label_31.setToolTip(_translate("MainWindow", "<html><head/><body><p>Минимальная длина участка регенерации ВОЛС<br><img src=\"./img/Lmin.jpg\"/></p></body></html>"))
        self.label_31.setText(_translate("MainWindow", "Lmin ="))
        self.label_32.setToolTip(_translate("MainWindow", "Строительная длина ВОЛС"))
        self.label_32.setText(_translate("MainWindow", "м"))
        self.label_33.setToolTip(_translate("MainWindow", "<html><head/><body><p>Максимальная длина участка регенерации ВОЛС<br><img src=\"./img/Lmax.jpg\"/></p></body></html>"))
        self.label_33.setText(_translate("MainWindow", "км"))
        self.label_34.setToolTip(_translate("MainWindow", "<html><head/><body><p>Минимальная длина участка регенерации ВОЛС<br><img src=\"./img/Lmin.jpg\"/></p></body></html>"))
        self.label_34.setText(_translate("MainWindow", "км"))
        self.label_35.setToolTip(_translate("MainWindow", "Количество разъемных соединений"))
        self.label_35.setText(_translate("MainWindow", "шт"))
        self.lineEdit_8.setToolTip(_translate("MainWindow", "<html><head/><body><p>Максимальная длина участка регенерации ВОЛС<br><img src=\"./img/Lmax.jpg\"/></p></body></html>"))
        self.lineEdit_16.setToolTip(_translate("MainWindow", "<html><head/><body><p>Минимальная длина участка регенерации ВОЛС<br><img src=\"./img/Lmin.jpg\"/></p></body></html>"))
        self.label_36.setToolTip(_translate("MainWindow", "Количество сварочных соединений"))
        self.label_36.setText(_translate("MainWindow", "шт"))
        self.spinBox_3.setToolTip(_translate("MainWindow", "Количество сварочных соединений"))
        self.spinBox_3.setSpecialValueText(_translate("MainWindow", "Введите..."))
        self.label_37.setToolTip(_translate("MainWindow", "Количество сварочных соединений"))
        self.label_37.setText(_translate("MainWindow", "Ncc ="))
        self.label_19.setText(_translate("MainWindow", "Расчет длины участка регенерации ВОЛС"))
        self.tab.setTabText(self.tab.indexOf(self.widget), _translate("MainWindow", "Расчёт параметров оптического кабеля"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

